services:
  - type: web
    name: shopnow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopnow.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopnow.settings
